default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("DB_USER") %>
  password: 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000


development:
  <<: *default
  database: <%= ENV.fetch("DEV_DB_NAME") %>

  
test:
  <<: *default
  database: <%= ENV.fetch("TEST_DB_NAME") %>


production:
  <<: *default
  database: <%= ENV.fetch("PRODUCTION_DB_NAME") %>

